name: Coralclimbtest
favicon: null
layout_spectrum: 0.06445001997053623
typography_spectrum: 0.7437945539131761
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2866559945978224
  lightness: 0.19229077082127333
  saturation: 0.5392997355666012
  rhythmicContrast: 0.5250391827430576
purpose: []
